baseURL: "https://johngunerli.com/"
languageCode: en-us
title: johngunerli
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: CV
      name: CV
      url: "https://drive.google.com/drive/folders/1oGVqzsSogTQFBSXsNNQk5X5MIUXGjVvI?usp=sharing"
      weight: 40

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "John Gunerli"
    subtitle: "Hi, I'm John Gunerli — Senior Machine Learning Engineer at UPS Capital and a Master's graduate in Computer Science from Georgia Institute of Technology. I work at the intersection of ML systems and people: computer vision, NLP, reinforcement learning, human-computer interaction, and human-robot interaction. I've done research at Georgia Tech, Purdue University, and Emory's Winship Cancer Institute."

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:hakancangunerli@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/hakancangunerli/"
    - name: "github"
      url: "https://github.com/johngunerli"
    - name: "youtube"
      url: "https://www.youtube.com/@johngunerli/"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
